--SQL Advance Case Study


--Q1--BEGIN --List all the states in which we have customers who have bought cellphones from 2005 till today. 
SELECT DISTINCT STATE
FROM DIM_LOCATION AS T1 LEFT JOIN FACT_TRANSACTIONS AS T2
ON 	T1.IDLOCATION= T2.IDLOCATION
LEFT join DIM_CUSTOMER AS T3
ON T3.IDCUSTOMER=T2.IDCUSTOMER
WHERE YEAR(DATE) > '2004'

--Q1--END

--Q2--BEGIN
--What state in the US is buying the most 'Samsung' cell phones?

SELECT TOP 1 T1.STATE,T1.COUNTRY,MANUFACTURER_NAME, COUNT(idcustomer) AS 'NUMBER OF SAMSUNG PHONES SOLD'
FROM DIM_LOCATION AS T1 LEFT JOIN FACT_TRANSACTIONS AS T2
ON T1.IDLOCATION=T2.IDLOCATION
LEFT JOIN DIM_MODEL AS T3
ON T3.IDMODEL=T2.IDMODEL
LEFT JOIN DIM_MANUFACTURER AS T4
ON T4.IDMANUFACTURER=T3.IDMANUFACTURER
WHERE T1.COUNTRY='US' AND T4.MANUFACTURER_NAME='SAMSUNG'
GROUP BY STATE,COUNTRY,MANUFACTURER_NAME
ORDER BY COUNT(*) DESC

--Q2--END

--Q3--BEGIN 
--Show the number of transactions for each model per zip code per state.      

SELECT T1.IDMODEL,MODEL_NAME,ZIPCODE,STATE,COUNT(IDCUSTOMER) AS 'NUMBER OF TRANSACTIONS'
FROM FACT_TRANSACTIONS AS T1 LEFT JOIN DIM_LOCATION AS T2
ON T1.IDLOCATION=T2.IDLOCATION
LEFT JOIN DIM_MODEL AS T3
ON T3.IDMODEL=T1.IDMODEL
GROUP BY T1.IDMODEL,ZIPCODE,STATE,MODEL_NAME

--Q3--END

--Q4--BEGIN
--Show the cheapest cellphone (Output should contain the price also)
SELECT  TOP 1 MODEL_NAME, MANUFACTURER_NAME, UNIT_PRICE AS PRICE
FROM DIM_MODEL AS T1 LEFT JOIN DIM_MANUFACTURER AS T2
ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
GROUP BY MODEL_NAME, MANUFACTURER_NAME, UNIT_PRICE
ORDER BY PRICE ASC

--Q4--END

--Q5--BEGIN
--Find out the average price for each model in the top5 manufacturers in terms of sales quantity and order by average price. 
SELECT MANUFACTURER_NAME,MODEL_NAME ,AVG(TOTALPRICE) AS 'AVERAGE PRICE',SUM(QUANTITY) AS 'SALES_QUANTITY'
FROM FACT_TRANSACTIONS AS T1 LEFT JOIN DIM_MODEL AS T2
ON T1.IDMODEL=T2.IDMODEL
LEFT JOIN DIM_MANUFACTURER AS T3
ON T3.IDMANUFACTURER= T2.IDMANUFACTURER
WHERE MANUFACTURER_NAME IN (SELECT TOP 5 MANUFACTURER_NAME 
							FROM FACT_TRANSACTIONS AS T1 LEFT JOIN DIM_MODEL AS T2
							ON T1.IDMODEL=T2.IDMODEL
							LEFT JOIN DIM_MANUFACTURER AS T3
							ON T3.IDMANUFACTURER= T2.IDMANUFACTURER 
							GROUP BY MANUFACTURER_NAME
							ORDER BY SUM(QUANTITY) DESC)
GROUP BY MANUFACTURER_NAME, MODEL_NAME
ORDER BY 'AVERAGE PRICE' ASC


--Q5--END

--Q6--BEGIN
--List the names of the customers and the average amount spent in 2009, where the average is higher than 500 
SELECT CUSTOMER_NAME, AVG(TOTALPRICE) AS AVG_PRICE
FROM DIM_DATE AS T1 LEFT JOIN FACT_TRANSACTIONS AS T2
ON T1.DATE=T2.DATE
LEFT JOIN DIM_CUSTOMER AS T3
ON T2.IDCUSTOMER=T3.IDCUSTOMER
WHERE YEAR='2009'
GROUP BY CUSTOMER_NAME
HAVING AVG(TOTALPRICE)>500

--Q6--END
	
--Q7--BEGIN 
--List if there is any model that was in the top 5 in terms of quantity, simultaneously in 2008, 2009 and 2010  
SELECT TOP 5 MODEL_NAME
FROM DIM_DATE AS T1 LEFT JOIN FACT_TRANSACTIONS AS T2
ON T1.DATE=T2.DATE
LEFT JOIN DIM_MODEL AS T3
ON T3.IDMODEL=T2.IDMODEL
WHERE YEAR='2008'
INTERSECT
SELECT TOP 5 MODEL_NAME
FROM DIM_DATE AS T1 LEFT JOIN FACT_TRANSACTIONS AS T2
ON T1.DATE=T2.DATE
LEFT JOIN DIM_MODEL AS T3
ON T3.IDMODEL=T2.IDMODEL
WHERE YEAR='2009'
INTERSECT
SELECT TOP 5 MODEL_NAME
FROM DIM_DATE AS T1 LEFT JOIN FACT_TRANSACTIONS AS T2
ON T1.DATE=T2.DATE
LEFT JOIN DIM_MODEL AS T3
ON T3.IDMODEL=T2.IDMODEL
WHERE YEAR='2010'	


--Q7--END	


--Q8--BEGIN
--Show the manufacturer with the 2nd top sales in the year of 2009 and the manufacturer with the 2nd top sales in the year of 2010. 
SELECT  top 1 * 
from (SELECT TOP 2 Manufacturer_name,SUM(Quantity ) AS QUANTITY2009, SUM(TOTALPRICE) AS PRICE2010
	FROM Fact_Transactions AS T1 LEFT JOIN DIM_Model AS T2
	ON T1.IDModel = T2.IDModel
    LEFT JOIN DIM_MANUFACTURER AS T3  
	ON T3.IDManufacturer = T2.IDManufacturer
    Where DATEPART(Year,date)='2009' 
    group by Manufacturer_name
    Order by  SUM(Quantity ) DESC) AS A, 
( SELECT Top 2 Manufacturer_name , SUM(QUANTITY) AS QUANTITY2010, SUM(TOTALPRICE ) AS PRICE2010
    FROM Fact_Transactions T4 LEFT JOIN DIM_Model T5 
	ON T4.IDModel = T5.IDModel
    LEFT JOIN DIM_MANUFACTURER T6  
	ON T6.IDManufacturer = T5.IDManufacturer
    Where DATEPART(Year,date)='2010' 
    group by Manufacturer_name
    Order by  SUM(TOTALPRICE)DESC) AS B

--Q8--END


--Q9--BEGIN
--Show the manufacturers that sold cellphones in 2010 but did not in 2009

SELECT  DISTINCT T4.*
FROM DIM_DATE AS T1 LEFT JOIN FACT_TRANSACTIONS AS T2
ON T1.DATE=T2.DATE
LEFT JOIN DIM_MODEL AS T3
ON T3.IDMODEL=T2.IDMODEL
LEFT JOIN DIM_MANUFACTURER AS T4
ON T4.IDMANUFACTURER=T3.IDMANUFACTURER
WHERE YEAR='2010'
EXCEPT 
SELECT  DISTINCT T4.*
FROM DIM_DATE AS T1 LEFT JOIN FACT_TRANSACTIONS AS T2
ON T1.DATE=T2.DATE
LEFT JOIN DIM_MODEL AS T3
ON T3.IDMODEL=T2.IDMODEL
LEFT JOIN DIM_MANUFACTURER AS T4
ON T4.IDMANUFACTURER=T3.IDMANUFACTURER
WHERE YEAR='2009'


--Q9--END

--Q10--BEGIN
--Find top 100 customers and their average spend, average quantity by each year. Also find the percentage of change in their spend

SELECT TABLE1.CUSTOMER_NAME, TABLE1.YEAR, TABLE1.AVGSPENT, TABLE1.AVGQUANTITY,
CASE WHEN TABLE2.Year IS NOT NULL
        THEN FORMAT(CONVERT(DECIMAL(8,2),(TABLE1.AVGSPENT-TABLE2.AVGSPENT))/CONVERT(DECIMAL(8,2),TABLE2.AVGSPENT),'p') ELSE NULL 
        END AS 'YEARLY_%_CHANGE'
FROM (SELECT CUSTOMER_NAME, YEAR(DATE) AS YEAR, AVG(TOTALPRICE) AS AVGSPENT, AVG(QUANTITY) AS AVGQUANTITY
		FROM DIM_CUSTOMER AS T1 LEFT JOIN FACT_TRANSACTIONS AS T2
		ON T1.IDCUSTOMER=T2.IDCUSTOMER
		WHERE T1.IDCUSTOMER IN (SELECT TOP 100 IDCUSTOMER
								FROM FACT_TRANSACTIONS
								GROUP BY IDCUSTOMER
								ORDER BY SUM(TOTALPRICE) DESC )
		GROUP BY CUSTOMER_NAME, YEAR(DATE) ) TABLE1
LEFT JOIN
	(SELECT CUSTOMER_NAME,YEAR(DATE) AS YEAR, AVG(TOTALPRICE) AS AVGSPENT, AVG(QUANTITY) AS AVGQUANTITY
	FROM DIM_CUSTOMER AS T1 LEFT JOIN FACT_TRANSACTIONS AS T2
		ON T1.IDCUSTOMER=T2.IDCUSTOMER

		WHERE T1.IDCUSTOMER IN (SELECT TOP 100 IDCUSTOMER
								FROM FACT_TRANSACTIONS
								GROUP BY IDCUSTOMER
								ORDER BY SUM(QUANTITY) DESC)
GROUP BY CUSTOMER_NAME, YEAR(DATE))  TABLE2
ON TABLE1.CUSTOMER_NAME=TABLE2.CUSTOMER_NAME AND TABLE1.YEAR=TABLE2.YEAR-1

--Q10--END
	